"""Static PerfectDraft catalogue lookup scraped from the public website."""
from __future__ import annotations

from typing import Any

PERFECTDRAFT_CATALOGUE: dict[str, dict[str, Any]] = {'1095': {'abv': '5%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe Ruby',
          'product_name': 'PerfectDraft Leffe Ruby 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD005',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Fruit Beer'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-ruby-6l-keg'},
 '2073': {'abv': '5.1%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hertog Jan'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Netherlands'},
          'name': 'Hertog Jan',
          'product_name': 'PerfectDraft Hertog Jan 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD008',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hertog-jan-6l-keg'},
 '2167': {'abv': '6.6%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe de Printemps',
          'product_name': 'PerfectDraft Leffe Spring 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD037',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Abbey Beer'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-spring-6l-keg'},
 '2172': {'abv': '6.5%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe Brune',
          'product_name': 'PerfectDraft Leffe Brune 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD022',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Brown Ale'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-brune-6l-keg'},
 '2452': {'abv': '7.5%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe Royale',
          'product_name': 'PerfectDraft Leffe Royal Whitbread Golding 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD016',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Strong Ale'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-royal-cascade-ipa-6l-keg'},
 '2565': {'abv': '3%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hoegaarden'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Hoegaarden Rosée',
          'product_name': 'PerfectDraft Hoegaarden Rose 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD021',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Fruit Beer'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hoegaarden-rose-6l-keg'},
 '29745': {'abv': '6.1%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Lowenbrau'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': 'Lowenbrau Oktoberfestbier',
           'product_name': 'PerfectDraft Lowenbrau Oktoberfestbier 6L Keg',
           'size': '6L',
           'sku': 'PD031',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-lowenbrau-oktoberfest-6lkeg'},
 '29775': {'abv': '4.1%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Goose Island'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'America'},
           'name': 'Goose Midway Session IPA',
           'product_name': 'PerfectDraft Goose Island Midway 6L Keg',
           'size': '6L',
           'sku': 'PD030',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-goose-island-midway-6l-keg'},
 '29896': {'abv': '8.4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Bosteels Brewery'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Kwak Ambrée',
           'product_name': 'PerfectDraft Kwak 6L Keg',
           'serving_temperature': '6°C',
           'size': '6L',
           'sku': 'PD032',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Amber Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-kwak-6l-keg'},
 '29974': {'abv': '5.2%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Spaten-Franziskaner-Bräu'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': 'Spaten',
           'product_name': 'PerfectDraft Spaten 6L Keg',
           'serving_temperature': '6°C',
           'size': '6L',
           'sku': '3663947047469',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-spaten-6l-beer-keg'},
 '30955': {'abv': '6%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Spaten-Franziskaner-Bräu'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': 'Franziskaner Royal',
           'product_name': 'PerfectDraft Franziskaner Royal 6L Keg',
           'size': '6L',
           'sku': 'PD038',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Wheat Beer'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-franziskaner-royal-6l-keg'},
 '31718': {'abv': '5.2%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Leffe Summer Blonde Ale',
           'product_name': 'PerfectDraft Leffe Summer 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD046',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Abbey Beer'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-summer-6l-keg'},
 '31896': {'abv': '8%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Bosteels Brewery'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Tripel Karmeliet',
           'product_name': 'PerfectDraft Tripel Karmeliet 6L Keg',
           'size': '6L',
           'sku': 'PD040',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Tripel'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-tripel-karmeliet-6l-keg'},
 '32814': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Birra del Borgo'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Italy'},
           'name': 'Romola',
           'product_name': 'PerfectDraft Birra Del Borgo Lisa 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD042',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-birra-del-borgo-lisa-6l-keg'},
 '32816': {'abv': '5.9%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Goose Island'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'America'},
           'name': 'Goose Island IPA',
           'product_name': 'PerfectDraft Goose Island IPA 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD043',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-goose-island-ipa-6l-keg'},
 '32864': {'abv': '6.6%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Leffe Ambrée',
           'product_name': 'PerfectDraft Leffe Amber 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD049',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Amber Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-amber-6l-keg'},
 '33642': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brasserie La Binchoise'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Ginette Bio Refreshing Blonde',
           'product_name': 'PerfectDraft Ginette Bio Refreshing Blonde 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD077',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-ginette-bio-refreshing-blonde-6l-keg'},
 '33917': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Tiny Rebel'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Tiny Rebel Clwb Tropica',
           'product_name': 'PerfectDraft Tiny Rebel Clwb Tropica 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD052',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-tiny-rebel-clwb-tropica-6l-keg'},
 '33918': {'abv': '5.9%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Spaten-Franziskaner-Bräu'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': 'Spaten Oktoberfestbier',
           'product_name': 'PerfectDraft Spaten Oktoberfestbier 6L Keg',
           'serving_temperature': '4–7°C',
           'size': '6L',
           'sku': 'PD053',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-spaten-oktoberfest-6l-keg'},
 '34493': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Corona'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Mexico'},
           'name': 'Corona Extra',
           'product_name': 'PerfectDraft Corona Extra 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD058',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-corona-extra-6l-keg'},
 '34592': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Groupo Modelo'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Mexico'},
           'name': 'Corona Extra Starter Bundle',
           'product_name': 'PerfectDraft Corona Extra Starter Bundle',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': '3663947010166',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-corona-extra-starter-bundle'},
 '34944': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Leffe la Légère',
           'product_name': 'PerfectDraft Leffe La Légère 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD061',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-la-legere-6l-keg'},
 '35344': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brasserie La Binchoise'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Ginette Bio White',
           'product_name': 'PerfectDraft Ginette Bio White 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD065',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Wheat Beer'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-ginette-bio-white-6l-keg'},
 '3550': {'abv': '6.6%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe Winter',
          'product_name': 'PerfectDraft Leffe Winter 6L Keg',
          'serving_temperature': '6°C',
          'size': '6L',
          'sku': 'PD013',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Amber Ale'},
          'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-christmas-6l-keg'},
 '36302': {'abv': '4%',
           'brewery': {'code': 'brewery',
                       'label': 'Brewery',
                       'value': 'Tennent Caledonian Breweries'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Tennents Lager',
           'product_name': "PerfectDraft Tennent's Lager 6L Keg",
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD073',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-tennent-s-lager-6l-keg'},
 '41588': {'abv': '4.9%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'G. Schneider and Sohn'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': "Schneider's Bayrisch Hell",
           'product_name': "PerfectDraft Schneider's Bayrisch Hell 6L Keg",
           'size': '6L',
           'sku': 'PD076',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-schneider-s-bayrisch-hell-6l-keg'},
 '41830': {'abv': '5.4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brewdog'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Brewdog Punk IPA',
           'product_name': 'PerfectDraft BrewDog Punk IPA 6L Keg',
           'serving_temperature': '6°C',
           'size': '6L',
           'sku': 'PD078',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-brewdog-punk-ipa-keg-6l'},
 '42223': {'abv': '8.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Victoria'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Victoria',
           'product_name': 'PerfectDraft Victoria 6L Keg',
           'size': '6L',
           'sku': 'PD081',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Strong Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-victoria-strong-blonde-ale-6l-keg'},
 '42352': {'abv': '7%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brasserie St-Feuillien'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Saint Feuillien Blonde',
           'product_name': 'PerfectDraft St Feuillien Blonde 6L Keg',
           'serving_temperature': '7°C',
           'size': '6L',
           'sku': 'PD086',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Abbey Beer'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-st-feuillien-blonde-6l-keg'},
 '42526': {'abv': '6.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Vocation'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Vocation Life & Death IPA',
           'product_name': 'PerfectDraft Vocation Life & Death 6L Keg',
           'size': '6L',
           'sku': 'PD082',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-vocation-life-death-6l-keg'},
 '42640': {'abv': '7.4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Bosteels Brewery'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Kwak Blonde',
           'product_name': 'PerfectDraft Kwak Blonde 6L Keg',
           'serving_temperature': '8°C',
           'size': '6L',
           'sku': 'PD090',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Strong Blonde Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-kwak-blonde-6l-keg'},
 '42756': {'abv': '4.6%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Innis & Gunn'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Innis & Gunn Lager',
           'product_name': 'PerfectDraft Innis & Gunn Lager Beer 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD092',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-innis-and-gunn-lager-6l-keg'},
 '42778': {'abv': '4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Mikkeller'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Denmark'},
           'name': 'Mikkeller Game of Thrones',
           'product_name': 'PerfectDraft Mikkeller Game of Thrones 6L Keg',
           'serving_temperature': '4-7°C',
           'size': '6L',
           'sku': 'PD093',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Pale Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-mikkeller-direwolf-brigade-pale-ale-6l-keg'},
 '42832': {'abv': '-',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'PerfectDraft'},
           'name': 'Pint Glass Pack (2 Glasses)',
           'product_name': 'PerfectDraft Pint Glass Pack (2 Glasses)',
           'sku': '3663947032465',
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-pint-glass-pack-2-glasses'},
 '42863': {'abv': '0',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'PerfectDraft'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'France'},
           'name': '1L Stein',
           'product_name': 'PerfectDraft 1L Stein',
           'sku': 'PDG55',
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-stein-pack'},
 '42876': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Orchard Pig'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Orchard Pig Reveller',
           'product_name': 'PerfectDraft Orchard Pig Reveller Cider 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD083',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Cider'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-orchard-pig-reveller-cider-6l-keg'},
 '43006': {'abv': '4.6%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Camden Town'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Camden Hells Lager',
           'product_name': 'PerfectDraft Camden Hells Lager 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': 'PD096',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-camden-hells-6l-keg'},
 '43009': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Stella Artois'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Stella Artois Unfiltered',
           'product_name': 'PerfectDraft Stella Artois Unfiltered 6L Keg',
           'size': '6L',
           'sku': 'PD080',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-stella-artois-unfiltered-6l-keg'},
 '43019': {'abv': '4.8%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hawkstone'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Hawkstone Lager',
           'product_name': 'PerfectDraft Hawkstone Lager 6L Keg',
           'size': '6L',
           'sku': 'PD094',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hawkstone-lager-6l-keg'},
 '43033': {'abv': '6.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hertog Jan'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Netherlands'},
           'name': 'Hertog Jan Bockbier',
           'product_name': 'PerfectDraft Hertog Jan Bockbier 6L Keg',
           'serving_temperature': '4-7°C',
           'size': '6L',
           'sku': 'PD100',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Bock'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hertog-jan-bock-bier'},
 '43064': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Groupo Modelo'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Mexico'},
           'name': 'Pro Corona Extra Starter Bundle',
           'product_name': 'PerfectDraft Pro Corona Extra Starter Bundle',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': '3663947010203',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-pro-corona-extra-starter-bundle'},
 '43130': {'abv': '0',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Camden Town'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Camden Jack Pint Glass Pack (2 Glasses)',
           'product_name': 'Camden Jack Pint Glass Pack (2 Glasses)',
           'sku': '3663947023791',
           'url': 'https://www.perfectdraft.com/en-gb/camden-jack-pint-glass-pack'},
 '43235': {'abv': '0.0%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Corona'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Mexico'},
           'name': 'Corona Cero',
           'product_name': 'PerfectDraft Corona Cero (0.0% abv) 6L Keg ',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': '5410228308430',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-corona-cero-0-0-6l-keg'},
 '43805': {'abv': '4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Camden Town'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Camden Pale',
           'product_name': 'PerfectDraft Camden Pale Ale 6L Keg',
           'size': '6L',
           'sku': '5410228313397',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Pale Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-camden-pale-ale-6l-keg'},
 '43806': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Magic Rock'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Magic Rock Chocolate Orange Stout',
           'product_name': 'PerfectDraft Magic Rock Magic Orange 6L Keg',
           'serving_temperature': '7–10°C',
           'size': '6L',
           'sku': '5410228313014',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Stout'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-magic-rock-magic-orange-6l-keg'},
 '44059': {'abv': '5.4%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'San Miguel'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Spain'},
           'name': 'San Miguel Especial',
           'product_name': 'PerfectDraft San Miguel Especial 6L Keg',
           'size': '6L',
           'sku': '110657',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-san-miguel-especial-6l-keg-2'},
 '44171': {'abv': '5.7%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
           'name': 'Leffe Blanche',
           'product_name': 'PerfectDraft Leffe Blanche 6L Keg',
           'size': '6L',
           'sku': '5410228315162',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Wheat Beer'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-blanche-6l-keg'},
 '44238': {'abv': '4.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brewdog'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Brewdog Hopped In Harmony',
           'product_name': 'PerfectDraft BrewDog Hopped in Harmony 6L Keg',
           'serving_temperature': '3°C',
           'size': '6L',
           'sku': '5014379026993',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-brewdog-hopped-in-harmony-ipa-6l-keg'},
 '44331': {'abv': '6.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Ninkasi Brasserie'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'France'},
           'name': 'Short Date Ninkasi Flower Lager 6L Keg BBE June 2024',
           'product_name': 'Short Date Ninkasi Flower Lager 6L Keg BBE June 2024',
           'serving_temperature': '4-7°C',
           'size': '6L',
           'sku': '5410228317425_SHORT',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-ninkasi-flower-lager-6l-keg-1'},
 '44387': {'abv': '6.5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brasserie du Mont Blanc'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'France'},
           'name': 'La Rousse du Mont Blanc',
           'product_name': 'PerfectDraft Mont Blanc La Rousse 6L Keg',
           'serving_temperature': '5°C',
           'size': '6L',
           'sku': '5410228317401',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Amber Ale'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-mont-blanc-la-rousse'},
 '44452': {'abv': '5.2%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Spaten-Franziskaner-Bräu'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
           'name': 'Franziskaner Kellerbier',
           'product_name': 'PerfectDraft Franziskaner Kellerbier 6L Keg',
           'size': '6L',
           'sku': '5410228317869',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Kellerbier'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-franziskaner-kellerbier-6l-keg'},
 '44474': {'abv': '5.7%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Camden Town'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Camden Marzen',
           'product_name': 'PerfectDraft Camden Marzen 6L Keg',
           'size': '6L',
           'sku': '5410228318422',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-camden-marzen-6l-keg'},
 '44536': {'abv': '5.2%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Tiny Rebel'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Short Date Tiny Rebel Stay Puft 6L Keg BBE August 2024',
           'product_name': 'Short Date Tiny Rebel Stay Puft 6L Keg BBE August 2024',
           'serving_temperature': '8°C',
           'size': '6L',
           'sku': '5410228318316_SHORT',
           'style': {'code': 'style', 'label': 'Style', 'value': 'Porter'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-tiny-rebel-stay-puft-6l-keg-1'},
 '452': {'abv': '4.9%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Becks'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
         'name': "Beck's Gold",
         'product_name': "PerfectDraft Beck's Gold 6L Keg",
         'serving_temperature': '3°C',
         'size': '6L',
         'sku': 'PD047',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-beck-s-gold-6l-keg'},
 '453': {'abv': '4.9%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Becks'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
         'name': "Beck's",
         'product_name': "PerfectDraft Beck's 6L Keg",
         'serving_temperature': '3°C',
         'size': '6L',
         'sku': 'PD023',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Pilsner'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-becks-6l-keg'},
 '455': {'abv': '5%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Spaten-Franziskaner-Bräu'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
         'name': 'Franziskaner Weissbier',
         'product_name': 'PerfectDraft Franziskaner Weissbier 6L Keg',
         'serving_temperature': '5°C',
         'size': '6L',
         'sku': 'PD007',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Wheat Beer'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-franziskaner-weissbier-6l-keg'},
 '456': {'abv': '4.9%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brauerei Diebels'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
         'name': 'Diebels',
         'product_name': 'PerfectDraft Diebels 6L Keg',
         'serving_temperature': '3°C',
         'size': '6L',
         'sku': 'PD018',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-diebels-6l-keg'},
 '458': {'abv': '5.2%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Jupiler'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
         'name': 'Jupiler',
         'product_name': 'PerfectDraft Jupiler 6L Keg',
         'serving_temperature': '3°C',
         'size': '6L',
         'sku': 'PD019',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Pilsner'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-jupiler-6l-keg'},
 '47486': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Brasserie Meteor'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'France'},
           'name': 'Meteor White IPA',
           'product_name': 'PerfectDraft Meteor White IPA 6L Keg',
           'serving_temperature': '8°C',
           'size': '6L',
           'sku': '5410228325512',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/meteor-white-ipa-6l-keg'},
 '47629': {'abv': '5%',
           'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Camden Town'},
           'country': {'code': 'country', 'label': 'Country', 'value': 'Britain'},
           'name': 'Camden Eazy IPA',
           'product_name': 'PerfectDraft Camden Eazy IPA 6L Keg',
           'serving_temperature': '4-7°C',
           'size': '6L',
           'sku': '5410228326205',
           'style': {'code': 'style', 'label': 'Style', 'value': 'IPA'},
           'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-camden-eazy-ipa-6l-keg'},
 '500': {'abv': '4.9%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hasseröder Brauerei'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Germany'},
         'name': 'Hasseroder',
         'product_name': 'PerfectDraft Hasseroder 6L Keg',
         'size': '6L',
         'sku': 'PD017',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Pilsner'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hasseroder-6l-keg'},
 '679': {'abv': '4.9%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Hoegaarden'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
         'name': 'Hoegaarden Blanche',
         'product_name': 'PerfectDraft Hoegaarden 6L Keg',
         'size': '6L',
         'sku': 'PD006',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Wheat Beer'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-hoegaarden-6l-keg'},
 '687': {'abv': '0',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
         'name': 'Leffe Half Pint Glass Pack (2 Glasses)',
         'product_name': 'Leffe Half Pint Glass Pack (2 Glasses)',
         'sku': '3663947027591',
         'url': 'https://www.perfectdraft.com/en-gb/leffe-half-pint-glass-pack-2-glasses'},
 '759': {'abv': '5.1%',
         'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Diekirch'},
         'country': {'code': 'country', 'label': 'Country', 'value': 'Luxembourg'},
         'name': 'Diekirch Grand Cru',
         'product_name': 'PerfectDraft Diekirch Grand Cru 6L Keg',
         'serving_temperature': '3°C',
         'size': '6L',
         'sku': 'PD020',
         'style': {'code': 'style', 'label': 'Style', 'value': 'Lager'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-diekirch-grand-cru-6l-keg'},
 '9156': {'abv': '7.5%',
          'brewery': {'code': 'brewery', 'label': 'Brewery', 'value': 'Leffe'},
          'country': {'code': 'country', 'label': 'Country', 'value': 'Belgium'},
          'name': 'Leffe Royale Cascade',
          'product_name': 'PerfectDraft Leffe Royal Cascade 6L Keg',
          'serving_temperature': '3°C',
          'size': '6L',
          'sku': 'PD004',
          'style': {'code': 'style', 'label': 'Style', 'value': 'Strong Blonde Ale'},
         'url': 'https://www.perfectdraft.com/en-gb/perfectdraft-leffe-royal-ipa-6l-keg'}}

CATALOGUE_ALIASES: dict[str, str] = {
    "35168": "golden_goose",
    "43807": "brewdog_lost_lager",
}

CATALOGUE_OVERRIDES: dict[str, dict[str, Any]] = {
    "golden_goose": {
        "abv": "5%",
        "brewery": {"code": "brewery", "label": "Brewery", "value": "Goose Island"},
        "country": {"code": "country", "label": "Country", "value": "America"},
        "name": "Goose Island Golden Goose",
        "product_name": "PerfectDraft Goose Island Golden Goose Lager 6L Keg",
        "serving_temperature": "3°C",
        "size": "6L",
        "sku": "5410228305651",
        "style": {"code": "style", "label": "Style", "value": "Lager"},
        "url": "https://www.perfectdraft.com/en-gb/perfectdraft-goose-island-golden-goose-lager-6l-keg-2",
    },
    "brewdog_lost_lager": {
        "abv": "4.5%",
        "brewery": {"code": "brewery", "label": "Brewery", "value": "Brewdog"},
        "country": {"code": "country", "label": "Country", "value": "Britain"},
        "name": "BrewDog Lost Lager",
        "product_name": "PerfectDraft BrewDog Lost Lager 6L Keg",
        "serving_temperature": "3°C",
        "size": "6L",
        "sku": "5410228313144",
        "style": {"code": "style", "label": "Style", "value": "Lager"},
        "url": "https://www.perfectdraft.com/en-gb/perfectdraft-brewdog-lost-lager-6l-keg-1",
    },
}

def lookup_product(product_id: str | None) -> dict[str, Any]:
    """Return catalogue metadata for a PerfectDraft API product ID."""
    if not product_id:
        return {}
    product_id = str(product_id)
    product_id = CATALOGUE_ALIASES.get(product_id, product_id)
    if product_id in CATALOGUE_OVERRIDES:
        return CATALOGUE_OVERRIDES[product_id]
    return PERFECTDRAFT_CATALOGUE.get(product_id, {})
